// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZvshkIgYdz_1JSukO6d3JyJE9mP_NUgg',
    appId: '1:1019433110549:web:f93b72aac97af2256c921c',
    messagingSenderId: '1019433110549',
    projectId: 'govi-final-v3',
    authDomain: 'govi-final-v3.firebaseapp.com',
    storageBucket: 'govi-final-v3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNuBFVTE-TU8GzOugxsMduOtP1kMddxzc',
    appId: '1:1019433110549:android:123a567b0cf355786c921c',
    messagingSenderId: '1019433110549',
    projectId: 'govi-final-v3',
    storageBucket: 'govi-final-v3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWnKXbDhX9iY9zCEWOUjnncOVEDqzJm_c',
    appId: '1:1019433110549:ios:20869193ce7b484b6c921c',
    messagingSenderId: '1019433110549',
    projectId: 'govi-final-v3',
    storageBucket: 'govi-final-v3.firebasestorage.app',
    iosBundleId: 'com.example.goviApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWnKXbDhX9iY9zCEWOUjnncOVEDqzJm_c',
    appId: '1:1019433110549:ios:20869193ce7b484b6c921c',
    messagingSenderId: '1019433110549',
    projectId: 'govi-final-v3',
    storageBucket: 'govi-final-v3.firebasestorage.app',
    iosBundleId: 'com.example.goviApp',
  );

}